sonar.projectKey=sancho3010_split-expenses-app
sonar.organization=sancho3010

sonar.sources=app
sonar.tests=tests
sonar.python.version=3.12

# Reportes de linters
sonar.python.pylint.reportPaths=pylint-report.txt
sonar.python.flake8.reportPaths=flake8-report.txt

# Reporte de cobertura generado por pytest-cov
sonar.python.coverage.reportPaths=ci_unit_coverage.xml,ci_integration_coverage.xml

# Exclusiones
sonar.coverage.exclusions=**/tests/**,app/__init__.py

# Quality Gate
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
