server {
    listen 8080;
    server_name localhost;

    # Frontend: archivos estáticos
    # El ALB maneja el routing: /api/* va al backend, /* viene aquí
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
