sonar.projectKey=sancho3010_split-expenses-app
sonar.organization=sancho3010

sonar.sources=.
sonar.exclusions=node_modules/**,tests/**
sonar.tests=tests
sonar.test.inclusions=tests/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Quality Gate
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
